The Grand Request
marqueewinq/steesh pull request #5
Opened 2022-02-21 15:26 UTC by iSapron

2022-02-21 15:48 UTC, marqueewinq commented on renderer/renderer.py
> +dtlst = card_data_list()
Не стоит включать логику в тело скрипта. Это уменьшает extendability (нельзя переиспользовать функции, нельзя импортировать без execution, сложно тестировать, ...)

Подход лучше (предлагаю использовать fire):

```
import fire

def render_page_cli(library_path, deck_path, template_path = "default_teamplte") -> None:
  library_dict = ... # read from library_path into dict
  deck = ... # read from deck_path into list(pair(cardname, number of copies))
  render_path(library_dict, deck, template_path)

def render_path(...):
  # test this function in unit tests

if __name__ == "__main__":
  fire.Fire(render_page_cli)
```

По итогу такой подход обеспечивает тебе удобные для тестирования функции:
 - read library
 - read deck
 - render (library, deck, template) -> html

Тестировать render_cli не обязательно, потому что она прозрачная (transparent function, https://en.wikipedia.org/wiki/White-box_testing)

read функции легко тестировать (сделай 5-7 параметризованных теста, 2х happy + 3 кривых, например).

render функцию можно тестировать просто acceptance ("**не падает -- и ладно**")

2022-02-21 15:52 UTC, marqueewinq requested changes
В целом, не ужасно. Вот список задач:

 - Include `test_dataframe` as csv
 - Refactor renderer.py to use Fire
 - Add unit tests on parser & end-to-end test

2022-02-21 15:52 UTC, marqueewinq commented on renderer/renderer.py
> +        str(pair[0]) + 'out.pdf',
тоже параметр для render_cli

2022-02-21 15:52 UTC, marqueewinq commented on renderer/renderer.py
> +dtlst = card_data_list()
Не стоит включать логику в тело скрипта. Это уменьшает extendability (нельзя переиспользовать функции, нельзя импортировать без execution, сложно тестировать, ...)

Подход лучше (предлагаю использовать fire):

```
import fire

def render_page_cli(library_path, deck_path, template_path = "default_teamplte") -> None:
  library_dict = ... # read from library_path into dict
  deck = ... # read from deck_path into list(pair(cardname, number of copies))
  render_path(library_dict, deck, template_path)

def render_path(...):
  # test this function in unit tests

if __name__ == "__main__":
  fire.Fire(render_page_cli)
```

По итогу такой подход обеспечивает тебе удобные для тестирования функции:
 - read library
 - read deck
 - render (library, deck, template) -> html

Тестировать render_cli не обязательно, потому что она прозрачная (transparent function, https://en.wikipedia.org/wiki/White-box_testing)

read функции легко тестировать (сделай 5-7 параметризованных теста, 2х happy + 3 кривых, например).

render функцию можно тестировать просто acceptance ("**не падает -- и ладно**")

2022-02-21 15:52 UTC, marqueewinq commented on renderer/renderer.py
> +dtlst = card_data_list()
Потом, когда надо будет API layer писать, ты легко переиспользуешь эти функции -- при текущем подходе это невозможно

2022-02-21 15:52 UTC, marqueewinq commented on renderer/renderer.py
> +for pdf in pdfs:
Вероятно, лишнее

2022-02-21 15:55 UTC, iSapron commented
[ooo.pdf](https://github.com/marqueewinq/steesh/files/8110593/ooo.pdf)

2022-02-21 16:11 UTC, iSapron commented on renderer/renderer.py
> +for pdf in pdfs:
А к чему это? Там файлы в один собираются, и остальные удаляются.

2022-03-09 08:14 UTC, marqueewinq reviewed
lg, small things commented out

2022-03-09 08:14 UTC, marqueewinq commented on renderer/renderer.py
> +                zip(keys, [cell.value if (cell.value != "-" or cell.value==None) else "" for cell in row])
`cell is None`

2022-03-09 08:14 UTC, marqueewinq commented on renderer/renderer.py
> +            print(mtch)
nit?

2022-03-09 08:25 UTC, marqueewinq approved these changes

2022-03-09 08:32 UTC, merged